$primary = rgb(e4a767)
$surface = rgb(241f19)
$secondary = rgb(d6d65c)
$error = rgb(c58a56)
$tertiary = rgb(98cc66)
$surface_lowest = rgb(120f0c)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
