# Colors (Noctalia)

[colors.bright]
black = '#191919'
blue = '#ffb219'
cyan = '#f2f2f2'
green = '#18f24f'
magenta = '#cdcdcd'
red = '#ffffff'
white = '#ffffff'
yellow = '#f2e018'

[colors.cursor]
cursor = '#e69900'
text = '#111111'

[colors.normal]
black = '#111111'
blue = '#e69900'
cyan = '#cccccc'
green = '#00cc33'
magenta = '#a7a7a7'
red = '#dddddd'
white = '#e69900'
yellow = '#ccbb00'

[colors.primary]
background = '#111111'
foreground = '#e69900'

[colors.selection]
background = '#e69900'
text = '#111111'
