[colors.primary]
background = '#241f19'
foreground = '#f3f2f2'
 
[colors.cursor]
text = '#f3f2f2'
cursor = '#b6b3af' 
 
[colors.vi_mode_cursor]
text = '#241f19'
cursor = '#e4a767' 
 
[colors.search.matches]
foreground = '#302921' 
background = '#98cc66' 
 
[colors.search.focused_match]
foreground = '#302921' 
background = '#e4a767' 
 
[colors.footer_bar]
foreground = '#302921' 
background = '#e8e6e3' 
 
[colors.hints.start]
foreground = '#302921' 
background = '#d6d65c' 
 
[colors.hints.end]
foreground = '#302921' 
background = '#d6d65c' 
 
[colors.selection]
text = '#241f19'
background = '#e4a767'
 
 
[colors.normal]
black = '#181818' 
red = '#c58a56' 
green = '#e4a767' 
yellow = '#996733' 
blue = '#e4a767' 
magenta = '#98cc66' 
cyan = '#d6d65c' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 